config/routes.rb
Rails.application.routes.draw do

  resources :tickets, except: [:update, :destroy] do
    resources :replies
  end
  
  resources :states, except: [:destroy]
  resources :departments, except: [:destroy]

  devise_for :owners

  resources :owners, only: [:show]
  
  root to: "tickets#index"
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :owner
  belongs_to :department
  belongs_to :state
  validates :body, presence: true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_owner!
  
  def create
    @ticket = Ticket.find_by uniq_reference: params[:ticket_id]
    @reply = @ticket.replies.create(reply_params)
    if @reply.save
      flash[:notice] = "Reply created!"
      @ticket.update_attribute :state_id, reply_params[:state_id]
      @ticket.update_attribute :owner_id, reply_params[:owner_id]
      UserMailer.ticket_replied_email(@ticket.client_email, @ticket.uniq_reference, 
                                      request.host_with_port + ticket_path(@ticket),
                                      @reply.body, @ticket.state.name, @ticket.client_name).deliver
      redirect_to ticket_path(@ticket)
    else
      flash[:alert] = "Please write reply"
      redirect_to ticket_path(@ticket)
    end
  end

  private
    def reply_params
      params.require(:reply).permit(:body, :replyer, :current_owner_email, :owner_id, :state_id)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.haml
= form_for @reply, html: { class: "form form-horizontal reply" } do |f|
  .form-group
    = f.label :body, class: 'control-label'
    .controls
      = f.text_field :body, class: 'form-control', required: true
    = error_span(@reply[:body])
  .form-group
    = f.label :ticket_id, class: 'control-label'
    .controls
      = f.text_field :ticket_id, class: 'form-control', required: true
    = error_span(@reply[:ticket_id])
  .form-group
    = f.label :owner_id, class: 'control-label'
    .controls
      = f.text_field :owner_id, class: 'form-control', required: true
    = error_span(@reply[:owner_id])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), replies_path, :class => 'btn btn-default'

app/views/replies/create.html.haml
%h1 Replies#create
%p Find me in app/views/replies/create.html.haml

app/views/replies/edit.html.haml
- model_class = Reply
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/replies/index.html.haml
- model_class = Reply
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:ticket_id)
      %th= model_class.human_attribute_name(:owner_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @replies.each do |reply|
      %tr
        %td= link_to reply.id, reply_path(reply)
        %td= reply.body
        %td= reply.ticket_id
        %td= reply.owner_id
        %td=l reply.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_reply_path(reply), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), reply_path(reply), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_reply_path, :class => 'btn btn-primary'

app/views/replies/new.html.haml
- model_class = Reply
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/replies/show.html.haml
- model_class = Reply
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @reply.body
%p
  %strong= model_class.human_attribute_name(:ticket_id) + ':'
  %br
  = @reply.ticket_id
%p
  %strong= model_class.human_attribute_name(:owner_id) + ':'
  %br
  = @reply.owner_id


= link_to t('.back', :default => t("helpers.links.back")), replies_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_reply_path(@reply), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), reply_path(@reply), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'