config/routes.rb
Rails.application.routes.draw do

  resources :tickets, except: [:update, :destroy] do
    resources :replies
  end
  
  resources :states, except: [:destroy]
  resources :departments, except: [:destroy]

  devise_for :owners

  resources :owners, only: [:show]
  
  root to: "tickets#index"
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :tickets, inverse_of: :state, dependent: :destroy
  has_many :replies, inverse_of: :state, dependent: :destroy
  validates :name, presence: true
  before_destroy :check
  
  private
    def check
      if tickets.any? or replies.any?
        errors[:base] << "cannot delete state"
        return false
      end
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_owner!
  respond_to :html

  def index
    @states = State.all
    respond_with(@states)
  end

  def show
    respond_with(@state)
  end

  def new
    @state = State.new
    respond_with(@state)
  end

  def edit
  end

  def create
    @state = State.new(state_params)
    @state.save
    respond_with(@state)
  end

  def update
    @state.update(state_params)
    respond_with(@state)
  end

  private
    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.haml
= form_for @state, html: { class: "form form-horizontal state" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@state[:name])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), states_path, :class => 'btn btn-default'

app/views/states/edit.html.haml
- model_class = State
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/states/index.html.haml
- model_class = State
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @states.each do |state|
      %tr
        %td= link_to state.id, state_path(state)
        %td= state.name
        %td= state.created_at.strftime("%Y-%m-%d %H:%M:%S")
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_state_path(state), :class => 'btn btn-default btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_state_path, :class => 'btn btn-primary'

app/views/states/new.html.haml
- model_class = State
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/states/show.html.haml
- model_class = State
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @state.name


= link_to t('.back', :default => t("helpers.links.back")), states_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_state_path(@state), :class => 'btn btn-default'