config/routes.rb
Rails.application.routes.draw do

  resources :tickets, except: [:update, :destroy] do
    resources :replies
  end
  
  resources :states, except: [:destroy]
  resources :departments, except: [:destroy]

  devise_for :owners

  resources :owners, only: [:show]
  
  root to: "tickets#index"
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :tickets
  validates :name, presence: true
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_owner!
  respond_to :html

  def index
    @departments = Department.all
    respond_with(@departments)
  end

  def show
    respond_with(@department)
  end

  def new
    @department = Department.new
    respond_with(@department)
  end

  def edit
  end

  def create
    @department = Department.new(department_params)
    @department.save
    respond_with(@department)
  end

  def update
    @department.update(department_params)
    respond_with(@department)
  end

  private
    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.haml
= form_for @department, html: { class: "form form-horizontal department" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@department[:name])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), departments_path, :class => 'btn btn-default'

app/views/departments/edit.html.haml
- model_class = Department
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/departments/index.html.haml
- model_class = Department
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @departments.each do |department|
      %tr
        %td= link_to department.id, department_path(department)
        %td= department.name
        %td= department.created_at.strftime("%Y-%m-%d %H:%M:%S")
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_department_path(department), :class => 'btn btn-default btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_department_path, :class => 'btn btn-primary'

app/views/departments/new.html.haml
- model_class = Department
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/departments/show.html.haml
- model_class = Department
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @department.name


= link_to t('.back', :default => t("helpers.links.back")), departments_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_department_path(@department), :class => 'btn btn-default'