config/routes.rb
Rails.application.routes.draw do

  resources :tickets, except: [:update, :destroy] do
    resources :replies
  end
  
  resources :states, except: [:destroy]
  resources :departments, except: [:destroy]

  devise_for :owners

  resources :owners, only: [:show]
  
  root to: "tickets#index"
end

app/models/ticket.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class Ticket < ActiveRecord::Base
  has_many :replies
  belongs_to :department
  belongs_to :state
  belongs_to :owner
  validates :client_name, :client_email, :subject, :body, :department, presence: true
  validates_uniqueness_of :uniq_reference
  validates :client_email, email: true
  extend FriendlyId
  friendly_id :uniq_reference
  
  scope :filter_department, -> (department_id) { where department_id: department_id }
  scope :filter_state, -> (state_id) { where state_id: state_id }
  scope :filter_subject, -> (subject) { where("subject like ? or body like ? or uniq_reference like ?", 
                                              "%#{subject}%", "%#{subject}%", "%#{subject}%")}
  before_validation(on: :create) do
    self.uniq_reference = uniq_ref
  end

  private
    def char_gen
      ('A'..'Z').to_a.shuffle[0, 3].join
    end

    def hex_gen
      SecureRandom.hex(1).upcase
    end

    def uniq_ref
      char_gen + '-' + hex_gen + '-' + char_gen + '-' + hex_gen + '-' + char_gen
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show]
  respond_to :html
  helper_method :sort_column, :sort_direction

  def index
    @departments = Department.all
    @states = State.all
    @tickets = Ticket.where(nil)
    @tickets = @tickets.filter_department(filter_params[:filter_department_id]) if filter_params[:filter_department_id].present?
    @tickets = @tickets.filter_state(filter_params[:filter_state_id]) if filter_params[:filter_state_id].present?
    @tickets = @tickets.filter_subject(filter_params[:search]) if filter_params[:search].present?
    @tickets = @tickets.order(sort_column + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
    respond_with(@tickets)
  end

  def new
    @ticket = Ticket.new
    respond_with(@ticket)
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      flash[:notice] = "Ticket created!"
      respond_with(@ticket)
      UserMailer.ticket_added_email(@ticket.client_email, @ticket.uniq_reference, 
                                    request.host_with_port + ticket_path(@ticket), @ticket.client_name).deliver
    else
      flash[:alert] = "Please fill in correctly all the fields"
      respond_with(@ticket)
    end
  end

  def show
    respond_with(@ticket)
  end

  private
    def set_ticket
      @ticket = Ticket.find_by uniq_reference: params[:id]
    end

    def ticket_params
      params.require(:ticket).permit(:client_name, :client_email, :subject, :body, :department_id,
                                     :uniq_reference, :state_id, :ticket)
    end

    def filter_params
      params.permit(:ticket, :filter_department_id, :filter_state_id, :filter_owner_id, :search, :order)
    end

    def sort_column
      Ticket.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

end

app/helpers/tickets_helper.rb
module TicketsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/tickets/_form.html.haml
= form_for @ticket, html: { class: "form form-horizontal ticket" } do |f|
  .form-group
    = f.label :client_name, class: 'control-label'
    .controls
      = f.text_field :client_name, class: 'form-control', required: true
    = error_span(@ticket[:client_name])
  .form-group
    = f.label :client_email, class: 'control-label'
    .controls
      = f.text_field :client_email, class: 'form-control', required: true
    = error_span(@ticket[:client_email])
  .form-group
    = f.label :subject, class: 'control-label'
    .controls
      = f.text_field :subject, class: 'form-control', required: true
    = error_span(@ticket[:subject])
  .form-group
    = f.label :body, class: 'control-label'
    .controls
      = f.text_area :body, class: 'form-control', required: true
    = error_span(@ticket[:body])
  .form-group
    = f.label :department_id, class: 'control-label'
    .controls
      = collection_select(:ticket, :department_id, Department.all, :id, :name)
    = error_span(@ticket[:department_id])
  = f.hidden_field :uniq_reference, value: @uniq_ref
  = f.hidden_field :state_id, value: 1
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), tickets_path, :class => 'btn btn-default'

app/views/tickets/_form_filter.html.haml
%center
  %b Department:
  - @departments.each do |d|
    = link_to d.name, {:filter_department_id => d.id}, :class => 'btn btn-default btn-xs'
  %br
  %br
  %b Status:
  - @states.each do |s|
    = link_to s.name, {:filter_state_id => s.id}, :class => 'btn btn-default btn-xs'
  %br
  %br
  = form_tag request.original_url, :method => 'get', :class => 'form-inline' do
    %p
      = text_field :search, params[:search], :placeholder => 'Ref id, subject, body...', :class => 'form-control'
      = submit_tag "Search", :name => nil, :class => 'btn btn-default'

app/views/tickets/_form_reply.haml
%h2 Add a reply:
= form_for([@ticket, @ticket.replies.build]) do |f|
  .form-group
    .controls
      = f.text_area :body, class: 'form-control', required: true
    = error_span(@ticket[:body])
  
  .form-group
    = f.label 'Set status', class: 'control-label'
    .controls
      = collection_select(:reply, :state_id, State.all, :id, :name, {:selected => @ticket.state.id})
    = error_span(@ticket[:state_id])

  = f.hidden_field :current_owner_email, value: current_owner.email
  = f.hidden_field :owner_id, value: current_owner.id
  = f.submit nil,class: 'btn btn-primary'

app/views/tickets/_form_reply.html.haml
%h2 Add a reply:
= form_for([@ticket, @ticket.replies.build]) do |f|
  .form-group
    .controls
      = f.text_area :body, class: 'form-control', required: true
    = error_span(@ticket[:body])
  
  .form-group
    = f.label 'Set status', class: 'control-label'
    .controls
      = collection_select(:reply, :state_id, State.all, :id, :name, {:selected => @ticket.state.id})
    = error_span(@ticket[:state_id])

  = f.hidden_field :current_owner_email, value: current_owner.email
  = f.hidden_field :owner_id, value: current_owner.id
  = f.submit nil,class: 'btn btn-primary'

app/views/tickets/edit.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tickets/index.html.haml
- model_class = Ticket
.row.row-centered
  .col-xs-3.col-centered.col-max
    .item
      .page-header
        %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
      .content
  .col-xs-6.col-centered.col-max
    .item
      = render :partial => "form_filter"
      .content
  .col-xs-3.col-centered.col-max
    .item.text-right
      %br
      = link_to raw('<i class="glyphicon glyphicon-plus"> Submit ticket</i>'), new_ticket_path, :class => 'btn btn-primary btn-lg'
      .content

%table.table.table-striped.pretty
  %thead
    %tr
      %th= sortable "client_name"
      %th= sortable "client_email"
      %th= sortable "subject"
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:reference)
      %th= model_class.human_attribute_name(:department)
      %th= model_class.human_attribute_name(:state_id)
      %th= sortable "owner_id"
      %th= sortable "created_at"
      %th= model_class.human_attribute_name(:replies)
  %tbody
    - @tickets.each do |ticket|
      %tr
        %td= ticket.client_name
        %td= ticket.client_email
        %td= link_to ticket.subject, ticket_path(ticket)
        %td= ticket.body.length > 150 ? ticket.body[0..150] + '...' : ticket.body
        %td= ticket.uniq_reference
        -if ticket.department_id
          %td= ticket.department.name
        -if ticket.state_id
          %td= ticket.state.name
        -if ticket.owner_id
          %td= ticket.owner.email
        -else
          %td= ''
        %td= ticket.created_at.strftime("%Y-%m-%d %H:%M:%S")
        %td= ticket.replies.size

= will_paginate @collection, renderer: BootstrapPagination::Rails
  

app/views/tickets/new.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tickets/show.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:client_name) + ':'
  %br
  = @ticket.client_name
%p
  %strong= model_class.human_attribute_name(:client_email) + ':'
  %br
  = @ticket.client_email
%p
  %strong= model_class.human_attribute_name(:subject) + ':'
  %br
  = @ticket.subject
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @ticket.body
%p
  %strong= model_class.human_attribute_name(:uniq_reference) + ':'
  %br
  = @ticket.uniq_reference
%p
  %strong= model_class.human_attribute_name(:department_id) + ':'
  %br
  = @ticket.department.name
%p
  %strong= model_class.human_attribute_name(:state_id) + ':'
  %br
  = @ticket.state.name
- if @ticket.owner_id
  %p
    %strong= model_class.human_attribute_name(:owner_id) + ':'
    %br
    = @ticket.owner.email


= link_to t('.back', :default => t("helpers.links.back")), tickets_path, :class => 'btn btn-default'
- if @ticket.replies.last
  %h2 Replies


- @ticket.replies.each do |reply|
  %hr
  %p
    %strong= model_class.human_attribute_name(:support_email) + ':'
    = reply.current_owner_email
    %br
    %strong= model_class.human_attribute_name(:reply) + ':'
    = reply.body
    %br
    %strong= model_class.human_attribute_name(:state) + ':'
    = reply.state.name
    %br
    %strong= model_class.human_attribute_name(:created_at) + ':'
    = reply.created_at.strftime("%Y-%m-%d %H:%M:%S")

%br
- if owner_signed_in?
  = render :partial => "form_reply"